/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PayidCard {
        "payid": string;
        "tolerant": boolean;
    }
}
declare global {
    interface HTMLPayidCardElement extends Components.PayidCard, HTMLStencilElement {
    }
    var HTMLPayidCardElement: {
        prototype: HTMLPayidCardElement;
        new (): HTMLPayidCardElement;
    };
    interface HTMLElementTagNameMap {
        "payid-card": HTMLPayidCardElement;
    }
}
declare namespace LocalJSX {
    interface PayidCard {
        "payid"?: string;
        "tolerant"?: boolean;
    }
    interface IntrinsicElements {
        "payid-card": PayidCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "payid-card": LocalJSX.PayidCard & JSXBase.HTMLAttributes<HTMLPayidCardElement>;
        }
    }
}
